### ISSUE TITLE
Orphaned Term Relationship are not deleted #2

### ISSUE THREAD

**Issue by geeac** [lesterchan/wp-sweep#14]
Hi,

After sweeping orphaned term relationships, I get 63.190 Orphaned Term Relationships Processed, but the details line still shows Orphaned Term Relationship	63,190
The count was originally 64,000+ and after several sweeps got down to 63.190, but no matter how many more sweeps I do, it sticks to 63.190.

I've run your query from issue #1 , replaced wp_ prefix with my own table prefix and this is the result http://pastebin.com/tZETkmg5 Note that the same database is used by 3 wordpress installs with different table prefixes.

**Comment by lesterchan** [comment]
That means that WordPress itself is not allowing you to delete those. It might be the default term for something?

This is the code , you can run it. I added a var_dump() so you can get the WP_Error if it fails.
```
$query = $wpdb->get_results( "SELECT tr.object_id, tt.term_id, tt.taxonomy FROM $wpdb->term_relationships AS tr INNER JOIN $wpdb->term_taxonomy AS tt ON tr.term_taxonomy_id = tt.term_taxonomy_id WHERE tt.taxonomy != 'link_category' AND tr.object_id NOT IN (SELECT ID FROM $wpdb->posts)" );
				if( $query ) {
					foreach ( $query as $tax ) {
						var_dump( wp_remove_object_terms( intval( $tax->object_id ), intval( $tax->term_id ), $tax->taxonomy )  );
					}
					$message = sprintf( __( '%s Orphaned Term Relationships Processed', 'wp-sweep' ), number_format_i18n( sizeof( $query ) ) );
				}
```

**Comment by geeac** [comment]
Many thanks :)
