### ISSUE TITLE
Feature requests!

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [lesterchan/wp-sweep#15]
Hello, Lester!
I have 2 feature requests I hope you will take under consideration:
1. Add a checkbox under the Sweep All button to ignore unused terms ( checked by default )
2. Add the possibility to do a Sweep All ( that ignores unused terms ) on a skedule ( daily, weekly, every 2nd week and monthly )

Best regards,
Eusebiu

**Comment by collinbarrett** [comment]
Bump for suggestion 2. Setting an auto sweep all (save unused terms) on a schedule would be baller. Thanks for the great plugin!

**Comment by fearlex** [comment]
+1 on this too. I can't run Sweep All at all, since i don't want to remove unused terms. I have to do it one at a time, which sucks.

Also +1 on the scheduling. That would be great !

Thanks for an amazing plugin.
