### ISSUE TITLE
Orphaned Term Relationship Not Deleting!!!

### ISSUE THREAD

**Issue by vanndigitalnetworks** [lesterchan/wp-sweep#21]
The Orphaned Term Relationship count is 87. Every time I run the Sweep plugin, it says "Orphaned Term Relationship processing" but the count stays at 87. Any help with this issue will be appreciated.

URL: http://www.vanndigital.com/

**Comment by lesterchan** [comment]
That's means that probably when it gets deleted, some plugins creates it back again

**Comment by vanndigitalnetworks** [comment]
Guess it's something I can look into...

**Comment by vanndigitalnetworks** [comment]
I created this issue last year & I finally fixed it not too long ago...
