### ISSUE TITLE
Multisite?

### ISSUE THREAD

**Issue by paaljoachim** [lesterchan/wp-sweep#22]
Hi

I did a network activation for a multisite.
I would like to see a screen in the multisite section for cleaning the full multisite.
Can this be done? Do I have to go to each sub site and run it there? Or can it be run from the Network Admin?

Thanks.

**Comment by lesterchan** [comment]
You have to go each sub site and run it. It is meant to use on individual sites rather than a network sites.

**Comment by paaljoachim** [comment]
Ok thanks for the feedback Lester!

**Comment by colomet** [comment]
Don´t you like to have an option for a multisite administrator?

**Comment by kinstazach** [comment]
Upvoting for multisite support (e.g. iterating through tables based on blog_id and existing table prefix, and printing a report for each site of what it cleaned).  I use WP Sweep to clean non-WPMS but there is no e.g. --network option for `wp sweep --all`
