### ISSUE TITLE
WP Sweep doesn't complete

### ISSUE THREAD

**Issue by thinkaboutit** [lesterchan/wp-sweep#28]
Hi 

I'm using WP Sweep to delete a lot of revisions (nearly 1300) in a local environment (xampp).

After some hours the process was not completed, so I closed the page and I have found that only 50 revisions were deleted

How can I make it work?

thanks for your plugin and time

**Comment by lesterchan** [comment]
You have to keep running it. Your server timeout. You have to increase the time limit and memory limit

```
ini_set( 'memory_limit','2048M' );
ini_set( 'max_execution_time', 600 );
```

Other than that, there is really nothing else I can do.

**Comment by thinkaboutit** [comment]
Hi 
thanks for your prompt reply.

I have deactivated all plugins and now it works
It has deleted 1200 revisions in a blink of an eye.

Thanks!
have a nice day
