### ISSUE TITLE
Division by zero

### ISSUE THREAD

**Issue by EusebiuOprinoiu** [lesterchan/wp-sweep#3]
Hello, Lester!
First of all I want to say congrats for creating this plugin. I played with it on a test environment and I noticed there are warnings at the Comment Sweep section when no comments exist.
Warning: Division by zero in \wp-sweep\admin.php on lines 184, 202, 220, 238 and 256.

I'm also curious if you plan on adding automated sweeps like WP Optimize does.

**Comment by lesterchan** [comment]
Yea, I will add it in the future because it will be useful. I am closing this because it is duplicated issue of https://github.com/lesterchan/wp-sweep/issues/4 =)
