### ISSUE TITLE
Add support for Code Climate

### ISSUE THREAD

**Issue by bhubbard** [lesterchan/wp-sweep#32]
CodeClimate is free for open source projects, and now supports WordPress standards for PHPCodeSniffer. It would be great, and can be done by creating a simple config file.

Repo on CodeClimate
https://codeclimate.com/github/lesterchan/wp-sweep/

Example .codeclimate.yml
https://docs.codeclimate.com/docs/example-codeclimateyml

PHP Code Sniffer config instructions:
https://github.com/codeclimate/codeclimate-phpcodesniffer

**Comment by lesterchan** [comment]
Submit a Pull Request?
