### ISSUE TITLE
Taxonomies on objects other than posts are removed

### ISSUE THREAD

**Issue by Chouby** [lesterchan/wp-sweep#34]
Hi!

I am the author of [Polylang](https://wordpress.org/plugins/polylang/). A user reported some issues when using WP Sweep and Polylang together. In fact, he lost the language and translations relations of his categories and post tags.

Polylang is a multilingual plugin entirely based on taxonomies. It does defines taxonomies for posts (as usual) but also taxonomies for terms (it's not frequently used by developers but possible). I am not the inventor of the concept and I have also seen plugins having taxonomies for users (although I don't remember which one). I have never seen it in a plugin, but we could also imagine to create taxonomies on comments.

I had a very quick look at your code and found:
`$query = $wpdb->get_results( "SELECT tr.object_id, tr.term_taxonomy_id, tt.term_id, tt.taxonomy FROM $wpdb->term_relationships AS tr INNER JOIN $wpdb->term_taxonomy AS tt ON tr.term_taxonomy_id = tt.term_taxonomy_id WHERE tt.taxonomy != 'link_category' AND tr.object_id NOT IN (SELECT ID FROM $wpdb->posts)" ); `
Some other queries are similar in the way they exclude taxonomies and object ids.

I foresee 2 solutions to the issue:
1. Add a filter to exclude more taxonomies than just 'link_category' which I could use to add Polylang taxonomies to the exclusion list.
2. Add more object ids in your exclusion list. Not only posts but also terms and users. Potentially links (in case a plugin creates another taxonomy than 'link_category') and comments if you want to be on the safe side.

**Comment by lesterchan** [comment]
Thanks for this, let me know if you have any problem with the master. I added the filter wp_sweep_excluded_taxonomies

**Comment by Chouby** [comment]
Thanks. I made the test and it works ok for me. I updated Polylang accordingly.
