### ISSUE TITLE
Polylang

### ISSUE THREAD

**Issue by szepeviktor** [lesterchan/wp-sweep#40]
I think `language` and `post_translations` are swept out in "Orphaned Term Relationship" while belonging to Polylang.

Maybe Polylang should hook `wp_sweep_excluded_taxonomies`?

**Comment by lesterchan** [comment]
Sorry, I don't really get what you mean by this?

**Comment by szepeviktor** [comment]
When searching for Orphaned Term Relationship `language` and `post_translations` are found to be orphans although Polylang uses them.

**Comment by lesterchan** [comment]
Ah I see, Polylang https://wordpress.org/plugins/polylang/ ?

I think better for plugins to hook on it. Unless WP defaults includes it

**Comment by szepeviktor** [comment]
@lesterchan Is this MU plugin OK?

```
add_filter( 'wp_sweep_excluded_taxonomies', function( $excluded_taxonomies ) {
    $excluded_taxonomies[] = 'language';
    $excluded_taxonomies[] = 'post_translations';
    return $excluded_taxonomies;
} );
```

**Comment by lesterchan** [comment]
Yea looks ok
