### ISSUE TITLE
Strings variables number %1$s repeated

### ISSUE THREAD

**Issue by pedro-mendonca** [lesterchan/wp-sweep#41]
Hi @lesterchan,

In these lines, shouldn' it be `%1$s` and `%2$s`?
https://github.com/lesterchan/wp-sweep/blob/master/admin.php#L73
https://github.com/lesterchan/wp-sweep/blob/master/admin.php#L80
https://github.com/lesterchan/wp-sweep/blob/master/admin.php#L217
https://github.com/lesterchan/wp-sweep/blob/master/admin.php#L334
https://github.com/lesterchan/wp-sweep/blob/master/admin.php#L391

**Comment by lesterchan** [comment]
You are right! I will fix it =)
