### ISSUE TITLE
Compared to WP-Optimize 

### ISSUE THREAD

**Issue by fearlex** [lesterchan/wp-sweep#45]
Hi @lesterchan 

First of all, I love your plugin, love the slick design and specially that it is under top level Tools.

My question is simple.

Is there a difference in the sweeping between WP Sweep and WP-Optimize ?

Let me elaborate that:

Right now i install both plugins, since i'm a perfectionist that likes to keep the database as clean as possible. Now, i'm afraid of using just Sweep (which is the one i prefer to use) since i'm not sure if it cleans and optimize DB exactly the same as WP-Optimize. See what i mean ?

Does they clean different stuff that overlap most of them, or they clean the same ?

I just want to get rid of WP-Optimize, but i feel it cleans stuffs that WP Sweep don't. Hopefully viceversa.

Thanks in advance for the reply.

**Comment by lesterchan** [comment]
I can't really comment on this because I don't use WP-Optimize myself. I only look through their code.

**Comment by fearlex** [comment]
> because I don't use WP-Optimize myself

Enough said ! Thanks !!
