### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Amstramgram** [lesterchan/wp-sweep#46]
Hello,
i try to install your plugin on Wordpress Multisite 4.7.1 and i have this issue when i try to activate.
`L’extension n’a pas pu être activée, car elle a déclenché une erreur fatale.`

Thank you.

**Comment by lesterchan** [comment]
Can you check your error log to see what is the error?

**Comment by Amstramgram** [comment]
Yep, i can and i have this:
`[Fri Jan 13 14:56:29.139676 2017] [:error] [pid 31743] [client] FastCGI: server "/var/www/clients/client3/web77/cgi-bin/php5-fcgi-*-443-siteweb.org" stderr: PHP message: PHP Fatal error:  Cannot use object of type WP_Site as array in /var/www/clients/client3/web77/web/wp-content/plugins/wp-sweep/wp-sweep.php on line 872, referer: https://www.siteweb.org/wp-admin/network/plugins.php`

**Comment by lesterchan** [comment]
Try to download again https://github.com/lesterchan/wp-sweep/archive/master.zip, I fixed it

**Comment by szepeviktor** [comment]
https://github.com/lesterchan/wp-sweep/commit/a7e051b41992c5b0f6d55955047108d086babc84

**Comment by Amstramgram** [comment]
Thank you, works perfectly
