### ISSUE TITLE
Remove duplicated post meta doesn't work

### ISSUE THREAD

**Issue by lauwqui** [lesterchan/wp-sweep#47]
![image](https://cloud.githubusercontent.com/assets/16436030/25074818/6edf8818-2305-11e7-883c-817a01eb14f4.png)

Hey there,
I've had an issue recently with a plugin that duplicates indefinitely meta_keys for my Woocommerce products, so this plugin seemed like the right solution (I'm not sure how to do this myself in phpmyadmin..)

I have like 40000 duplicates.
But.. when I sweep, nothing happens, no error message, nothing..

I'm running this on a private SQL server.

Thank you for your help !
Bonjour de GamerZ !

**Comment by szepeviktor** [comment]
> with a plugin that duplicates indefinitely meta_keys

1) It seems to me that best solution is to track down `add_post_meta()` in that plugin.

2) When you deal with heavy websites, please consider using a direct (without bothering the webserver) software: WP-CLI
https://github.com/lesterchan/wp-sweep/blob/master/class-command.php

**Comment by lauwqui** [comment]
Hi,

Thanks for your answer.

Yeah, I figured it was something like that and I have no idea how to fix this myself.

And about WP-CLI, I've just discovered what this is, read the documentation, I have no idea not the faintest idea how to install this on my hosting...

**Comment by szepeviktor** [comment]
WP-CLI needs terminal access: SSH.

I you would have me find the glitch in that plugin or install WP-CLI drop me an email: https://github.com/szepeviktor
