### ISSUE TITLE
Be warned, this plugin may erase data (not just from Follow-ups, but it may harm your WooCommerce product data as well

### ISSUE THREAD

**Issue by fearlex** [lesterchan/wp-sweep#50]
Hi @lesterchan 

I recently switched from using Wp-Optimize to use Wp-Sweep, but after find this on the documentation of WooCommerce Follow-Up Emails plugin, i'm concerned.

![screen shot 2017-07-11 at 4 47 24 pm](https://user-images.githubusercontent.com/89010/28090078-1d1582b6-6659-11e7-8001-f1d760a5da5c.png)

Is this true ? I'm just concerned as i manage a lot of Woocommerce websites and wouldn't want data to be erased while doing an sweep.

Thanks for your reply in advanced.

**Comment by szepeviktor** [comment]
It may be about *Follow-Up Emails* stores some kind of data looking like orphaned items.

https://docs.woocommerce.com/document/automated-follow-up-emails-docs/faq/

**Comment by szepeviktor** [comment]
AFAIK it would be beneficial to concentrate of WC data loss.

**Comment by fearlex** [comment]
@szepeviktor Which is fine, if i were only for Follow-Up Emails but they say that it may harm Woocommerce product data as well. That's when i got concerned.

I think this is an amazing plugin, i just can afford to lose any relevant data for any of the woocommerce sites i manage.

**Comment by szepeviktor** [comment]
Have you asked WC support which *sweep* cause harm during their testing?

**Comment by fearlex** [comment]
Not really, i'm installing the Follow-Up emails for a client and saw that message while reading the FAQs, i chose to ask the plugin developer directly 😄
