### ISSUE TITLE
Improve bare implode

### ISSUE THREAD

**Issue by szepeviktor** [lesterchan/wp-sweep#51]
A custom builder method could 

- make it secure (each item sanitized and escaped) and
- more readable.

```php
// implode( '\',\'', $this->get_excluded_taxonomies() )
$this->build_sql_list( $this->get_excluded_taxonomies() )
```

**Comment by lesterchan** [comment]
Yeap I agree. Please send in a PR =D, because if it is up to me, I don't know when I will have time to look into this again lol. So busy with my day job.

**Comment by szepeviktor** [comment]
Notes:

`implode(", ", array_map('intval', $arr))`
`"'" . esc_sql( $string ) . "'"`

**Comment by szepeviktor** [comment]
> because if it is up to me, I don't know when I will have time to look into this

@lesterchan Any chance to implement it?

**Comment by lesterchan** [comment]
@szepeviktor fixed =)

**Comment by szepeviktor** [comment]
Thanks
