### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by szepeviktor** [lesterchan/wp-sweep#56]
~~Please add codeclimate and trvis bagdes to readme.~~
Move badges to the top!

**Comment by lesterchan** [comment]
I move it to the middle because I have a parser to convert README.md to WP readme.txt and it doesn't place nice with it being at it at the top. WordPress readme.txt is so outdated. I don't understand why they can't use README.md

**Comment by szepeviktor** [comment]
I see.
