### ISSUE TITLE
Compatible with Elementor

### ISSUE THREAD

**Issue by marufkusbianto** [lesterchan/wp-sweep#67]
As you mentioned in the documentation of this plugin that it does not work with elementor plugin on wordpress, is still not compatible yet till now? I need this plugin to clean up my junk database because of elementor plugin, my database become huge (for about 40 Gb) with elementor and multisite inside my hosting. Please let me know this compatibility, Thankyou before

**Comment by lesterchan** [comment]
I don't think so. I don't use elementor myself, so the compatibility is submitted by my users.

**Comment by marufkusbianto** [comment]
Thank you for the answer
